### ISSUE TITLE
Add 'develop documentation' to DocBot Indiegogo goals

### ISSUE THREAD

**Issue by ArloJamesBarnes** [tosdr/DocBot-Server#2]
currently:

> We have the following projects for improvement:
> An automated document annotator/reviewer (A.K.A. Docbot) — (Currently under development, viewable on our Discord Server.).

**Comment by JustinBack** [comment]
![grafik](https://user-images.githubusercontent.com/40178814/112687280-8e9f7780-8e77-11eb-8620-17de8d90bfb1.png)
Done :-)
